### ISSUE TITLE
Peer-to-peer - John

### ISSUE THREAD

**Issue by Rysth** [mahammad-mostafa/personal-portfolio-site#3]
### Opinions (Suggestions/Improvements)

- Good common CSS structure because of clean code.
- Good use of semantic HTML tags in general.
- Use of CSS variables in font names and colors to have more flexibility.
- Use a better Hierarchy on each HTML page to support SEO guidelines.
- Change the first `div` tag on the About Section which has the `about-top` class name to a `header` tag.

**Comment by mahammad-mostafa** [comment]
## 🖊️ Resolved with following actions

✅ Made use of CSS variables across different colors and fonts
✅ Changed first `div` tag in the about section to a `header` tag
✅ Added your contribution to the README file Acknowledgements section
